Models/Bookmark.cs
using System;

namespace Clara.Models
{
    public class Bookmark
    {
        public Guid BookmarkId { get; set; }
        public Guid ServiceId { get; set; }
        public Service Service { get; set; }
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
        public DateTime DateCreated { get; set; }
    }
}
 

Models/Service.cs
using System;
using System.Collections.Generic;

namespace Clara.Models
{
    public class Service
    {
        public Guid ServiceId { get; set; }
        public string BusinessName { get; set; }
        public string BusinessEmail { get; set; }
        public string PhoneNumber { get; set; }
        public string ImageURL { get; set; }
        public string AddressLine { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Description { get; set; }
        public string Amenities { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
        public UserProfile UserProfile { get; set; }
        public List<Bookmark> Bookmarks { get; set; }
        public List<Comment> Comments { get; set; }
    }
}

ViewModels/ServicesViewModel.cs
using Clara.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clara.ViewModels
{
    public class ServicesViewModel
    {
        public Guid ServiceId { get; set; }
        public string BusinessName { get; set; }
        public string BusinessEmail { get; set; }
        public string PhoneNumber { get; set; }
        //public decimal EstimatedPrice { get; set; }
        //public string ImageURL { get; set; }
        public string AddressLine { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        //public string Country { get; set; }
        //public string Description { get; set; }
        //public List<AddOns> AddOns { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
        public string ImageUrl { get; set; }
        public UserProfile UserProfile { get; set; }
        public List<Bookmark> Bookmarks { get; set; }
        public List<Comment> Comments { get; set; }

    }
}

Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Clara.Infrastructure;
using Clara.Models;
using Clara.Repository.Interface;
using Clara.Utility;
using Clara.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace Clara.Controllers
{
    public class ServiceController : Controller
    {
        
        private readonly IMapper _mapper;
        private readonly IRepositoryManager _repositoryManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHubContext<SignalServer> _hubContext;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ServiceController(IMapper mapper, IRepositoryManager repositoryManager, UserManager<ApplicationUser> userManager, IHubContext<SignalServer> hubContext, IWebHostEnvironment webHostEnvironment)
        {
            _mapper = mapper;
            _repositoryManager = repositoryManager;
            _userManager = userManager;
            _hubContext = hubContext;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateServiceViewModel model = new CreateServiceViewModel();

            var categoryList = _repositoryManager.Category.GetAllCategories.OrderBy(c => c.CategoryName).ToList();

            categoryList.Insert(0, new Category { CategoryId = 0, CategoryName = "--- Select A Category ---" });

            model.Categories = categoryList;

            return View(model);
        }

        public IActionResult Success()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(CreateServiceViewModel model)
        {
            if (ModelState.IsValid)
            {
                var service = _mapper.Map<Service>(model);
                service.ImageURL = ImagesUpload(model);
                 _repositoryManager.Service.CreateService(service);
                await _repositoryManager.saveAsync();
                return RedirectToAction(nameof(Success));
            }
            return View(model);
        }

      

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Services(Guid id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Services(int? pageNumber, string category, string location, string search)
        {
            int pageSize = 6;
            List<ServicesViewModel> services;
            string serviceTop = string.Empty;
            var locationIncluded = location ?? "All Location";

            //category List
            var categoryList = _repositoryManager.Category.GetAllCategories.OrderBy(c => c.CategoryName).ToList();
            categoryList.Insert(0, new Category { CategoryId = 0, CategoryName = "Select Category" });
            if (category == "Select Category")
                category = null;

            SearchParameters(category, location, search, out services, out serviceTop, locationIncluded);


            ViewBag.servicesTop = serviceTop;
            ViewBag.ServiceCount = services.Count();
            ViewBag.CategoryList = categoryList;

            return View(ServicesPagination<ServicesViewModel>.Create(services, pageSize, pageNumber ?? 1));
        }

        private void SearchParameters(string category, string location, string search, out List<ServicesViewModel> services, out string serviceTop, string locationIncluded)
        {
            if (!string.IsNullOrEmpty(category) && !string.IsNullOrEmpty(location) && !string.IsNullOrEmpty(search))
            {
                services = _repositoryManager.Service.GetServicesByLocationAndSearch(category, location, search)
                    .Select(service => _mapper.Map<ServicesViewModel>(service))
                    .ToList();

                serviceTop = $"{category} in {locationIncluded}, with search: {search}";
            }

            else if (!string.IsNullOrEmpty(category) && !string.IsNullOrEmpty(location))
            {
                services = _repositoryManager.Service.GetServicesByLocation(category, location)
                    .Select(service => _mapper.Map<ServicesViewModel>(service))
                    .ToList();

                serviceTop = $"{category} in {locationIncluded}";
            }

            else if (!string.IsNullOrEmpty(category))
            {
                services = _repositoryManager.Service.GetServicesByCategory(category)
                    .Select(service => _mapper.Map<ServicesViewModel>(service))
                    .ToList();

                serviceTop = $"{category} Services";
            }
            else if (!string.IsNullOrEmpty(location))
            {
                services = _repositoryManager.Service.GetServicesByLocation(location)
                    .Select(service => _mapper.Map<ServicesViewModel>(service))
                    .ToList();

                serviceTop = $"Services In {location}";
            }
            else if (!string.IsNullOrEmpty(search))
            {
                services = _repositoryManager.Service.GetServicesBySearch(search)
                    .Select(service => _mapper.Map<ServicesViewModel>(service))
                    .ToList();

                serviceTop = $"Service: {search}";
            }
            else
            {
                services = _repositoryManager.Service.GetAllService()
                    .Select(service => _mapper.Map<ServicesViewModel>(service))
                    .ToList();

                serviceTop = "All Services";
            }
        }

        [HttpGet]
        public async  Task<IActionResult> Details(Guid serviceId, int categoryId)
        {
            var service = await _repositoryManager.Service.GetServiceById(serviceId);

            var userId = _userManager.GetUserId(User);

            if (service == null)
                return View("Notfound");

            //Random Services
            var services = _repositoryManager.Service.GetRandomService(serviceId);
               
            //Comments
            var comments = _repositoryManager.Comment.GetComments(serviceId).ToList();

            //Rating
            var totalRating = Convert.ToInt32(TotalRating(serviceId));

            DetailsViewModel model = new DetailsViewModel
            {
                Service = service,
                RandomServices = services,
                Comments = comments,
                Amenities = formatAmenties(service),
                Rating = totalRating,
                ImagesUrl = formatImage(service),
                ImageUrl = formatImage(service)[0]
                
            };

            //Bookmark
            var bookmark = _repositoryManager.Bookmark.isServiceBookmarked(userId, serviceId);
            if (bookmark != null)
                model.isBookmarked = true;
            else
                model.isBookmarked = false;

            return View(model);
        }

        private int TotalRating(Guid serviceId)
        {
            var ratings = _repositoryManager.Comment.GetTotalServiceRating(serviceId);
            int total = 0;
            foreach (var rating in ratings)
            {
                total += rating;
            }
            if(ratings.Count() != 0)
                return total / ratings.Count();

            return 0;

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(DetailsViewModel model)
        {
            var userProfile = _repositoryManager.UserProfile.GetUserProfile(model.UserId);

            var service = await _repositoryManager.Service.GetServiceById(model.ServiceId);

            if (ModelState.IsValid)
            {
                var hasUserComment = _repositoryManager.Comment.HasUserComment(model.UserId, model.ServiceId);

               var comment =  _mapper.Map<Comment>(model);

                _repositoryManager.Comment.AddComment(comment);

                SendNotificationToUser(userProfile, service, comment);

                await _repositoryManager.saveAsync();
                await _hubContext.Clients.All.SendAsync("displayNotification", "");

                return RedirectToAction(nameof(Details), new { serviceId = model.ServiceId, categoryId = model.CategoryId });
            }

            return View(model);
        }

        private void SendNotificationToUser(UserProfile userProfile, Service service, Comment comment)
        {
            Notification notification = new Notification
            {
                Text = $"{userProfile.FirstName} {userProfile.LastName} left a review on {service.BusinessName} with a {comment.rating}.0 rating",
            };

            _repositoryManager.Notification.AddNotification(notification);

            NotificationApplicationUser userNotification = new NotificationApplicationUser();
            userNotification.NotificationId = notification.NotificationId;
            userNotification.UserId = service.User.Id;

            _repositoryManager.UserNotification.AddUserNotification(userNotification);
        }

        private string ImagesUpload(CreateServiceViewModel model)
        {
            string allFileName = string.Empty;

            if(model.Photos != null  && model.Photos.Count > 0)
            {
                foreach(var photo in model.Photos)
                {
                    string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + photo.FileName;

Views/User/Account.cshtml
@inject UserManager<ApplicationUser> appUser

@{ 
    Layout = "_PagesLayout";
    var userId = appUser.GetUserId(User);
}

<section class="py-5">
    <div class="container">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb #{breadcrumbClass}">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item active">Your account</li>
        </ol>
        <h1 class="hero-heading mb-0">Welcome, @ViewBag.firstName.</h1>
        <p class="text-muted mb-5">Manage your account and settings here.</p>
        <div class="row">
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#identity-1"> </use>
                            </svg>
                        </div>
                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" asp-action="Personal" asp-controller="User" asp-route-Id="@userId">Personal info</a></h5>
                        <p class="text-muted card-text text-sm">Provide personal details and how we can reach you</p>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#pay-by-card-1"> </use>
                            </svg>
                        </div>

                        <a asp-action="Create" asp-controller="Service" class="badge badge-transparent badge-pill px-3 py-2 float-right font-weight-bolder text-dark">Add Service</a>

                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" asp-action="Profile" asp-controller="User">Service</a></h5>
                        <p class="text-muted card-text text-sm">Review Services, Add Services, handle all activities related to your services</p>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#password-1"> </use>
                            </svg>
                        </div>
                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" asp-action="Security" asp-controller="User">Login &amp; security</a></h5>
                        <p class="text-muted card-text text-sm">Update your password and secure your account</p>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#password-1"> </use>
                            </svg>
                        </div>
                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" asp-action="Bookmark" asp-controller="User">BookMarks</a></h5>
                        <p class="text-muted card-text text-sm">Manage Your Bookmarks, View your bookmarks and delete unwanted bookmarks</p>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#chat-app-1"> </use>
                            </svg>
                        </div>
                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" href="#">Notifications</a></h5>
                        <p class="text-muted card-text text-sm">Choose notification preferences and how you want to be contacted</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div id="HideNotiText">

    </div>

    <!-- Modal 4 :: Notifications -->
    <div class="modal modal-lg-fullscreen fade" id="notificationModal" tabindex="-1" role="dialog" aria-labelledby="notificationModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-dialog-zoom">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="notificationModalLabel">Notifications</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body p-0 hide-scrollbar">
                    <div class="row">

                        <div class="col-12">
                            <!-- List Group Start -->
                            <ul class="list-group list-group-flush  py-2">

                                <!-- List Group Item Start -->
                                <li class="list-group-item">
                                    <div class="media">
                                        <div class="btn btn-primary btn-icon rounded-circle text-light mr-2">
                                            <!-- Default :: Inline SVG -->
                                            <svg class="hw-24" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                            </svg>

                                            <!-- Alternate :: External File link -->
                                            <!-- <img class="injectable hw-24" src="./../assets/media/heroicons/outline/check-circle.svg" alt=""> -->
                                        </div>

                                        <div class="media-body">
                                            <h6>
                                                <a href="#">Katelyn Valdez</a> accepted your friend request
                                            </h6>

                                            <p class="text-muted mb-0">25 mins ago</p>
                                        </div>
                                    </div>
                                </li>
                                <!-- List Group Item End -->

                            </ul>
                            <!-- List Group End -->
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-link text-muted">Clear all</button>
                </div>
            </div>
        </div>
    </div>

</section>

Views/User/Bookmark.cshtml
@model UserProfileViewModel

@{ 
    Layout = "_PagesLayout";

 }

<section class="py-5 mb-5">
    <div class="container">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb pl-0  justify-content-start">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Home">Home</a></li>
            <li class="breadcrumb-item"><a asp-action="Account" asp-controller="User">Account</a></li>
            <li class="breadcrumb-item active">Bookmarks </li>
        </ol>
        <div class="row">
            <div class="col-lg-12 pl-lg-5">
                <h1 class="hero-heading mb-0 text-center">HEY @Model.FirstName!</h1>
                <div class="text-block text-center">
                    <h5 id="main-text" class="text-muted">Here Are Your Currently Bookmarked Services <i class="fa fa-heart text-danger aria-hidden=" true""></i></h5>
                    @*<p class="text-muted">.......</p>*@
                </div>
                <div class="text-block">
                    <h4 class="mb-5">@Model.FirstName's BookMarks</h4>
                    <div class="row">
                        @if (Model.Bookmarks.Count == 0)
                        {
            <p>You have No services Bookmarked at them moment</p> }
        else
        {
            foreach (var bookmark in Model.Bookmarks)
            { <!-- place item-->

                                    <div class="col-sm-6 col-xl-4 mb-5 hover-animate" data-marker-id="59c0c8e33b1527bfe2abaf92">
                                        <div class="card border-0 shadow">
                                            <div class="card-img-top overflow-hidden dark-overlay bg-cover">
                                                <img src="~/img/listing/list-4.jpg" class="card-img" alt="Alternate Text" />
                                                <a class="tile-link" asp-action="Details" asp-controller="Service" asp-route-serviceId="@bookmark.Service.ServiceId" asp-route-categoryId="@bookmark.Service.CategoryId"></a>
                                                <div class="card-img-overlay-bottom z-index-20">
                                                    <h4 class="text-white text-shadow">@bookmark.Service.BusinessName</h4>
                                                    <p class="mb-2 text-xs">
                                                        <i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-warning"></i><i class="fa fa-star text-gray-300">                    </i>
                                                    </p>
                                                </div>
                                                <div class="card-img-overlay-top d-flex justify-content-between align-items-center">
                                                    <div class="badge badge-transparent badge-pill px-3 py-2">@bookmark.Service.Category.CategoryName</div><a class="card-fav-icon position-relative z-index-40" href="javascript: void();">
                                                        <svg class="svg-icon text-white">
                                                            <use xlink:href="#heart-1"> </use>
                                                        </svg>
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="card-body">
                                                <p class="text-sm text-muted mb-3">@bookmark.Service.AddressLine</p>
                                                <p class="text-sm text-muted mb-3">@bookmark.Service.PhoneNumber</p>
                                                <p class="text-sm text-muted text-uppercase mb-1">By <a href="#" class="text-dark"></a></p>
                                                <p class="text-sm mb-0">
                                                    <a class="mr-1" href="#">@bookmark.Service.Category.CategoryName,</a><a class="mr-1" href="#">Contemporary</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>}
                                                }


                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

Views/User/Index.cshtml
@{ 
    Layout = "_PagesLayout";
}

<section class="py-5">
    <div class="container">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb #{breadcrumbClass}">
            <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
            <li class="breadcrumb-item active">Your account   </li>
        </ol>
        <h1 class="hero-heading mb-0">Welcome, </h1>
        <p class="text-muted mb-5">Manage your account and settings here.</p>
        <div class="row">
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#identity-1"> </use>
                            </svg>
                        </div>
                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" href="user-personal.html">Personal info</a></h5>
                        <p class="text-muted card-text text-sm">Provide personal details and how we can reach you</p>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#pay-by-card-1"> </use>
                            </svg>
                        </div>
                        <div class="badge badge-transparent badge-pill px-3 py-2 float-right font-weight-bolder text-dark">
                            <a href="#">Add Service</a>
                        </div>
                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" href="#">Service</a></h5>
                        <p class="text-muted card-text text-sm">Review Services, Add Services, handle all activities related to your services</p>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#password-1"> </use>
                            </svg>
                        </div>
                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" href="user-security.html">Login &amp; security</a></h5>
                        <p class="text-muted card-text text-sm">Update your password and secure your account</p>
                    </div>
                </div>
            </div>
            <div class="col-6 col-md-4 mb-30px">
                <div class="card h-100 border-0 shadow hover-animate">
                    <div class="card-body">
                        <div class="icon-rounded bg-secondary-light mb-3">
                            <svg class="svg-icon text-secondary w-2rem h-2rem">
                                <use xlink:href="#chat-app-1"> </use>
                            </svg>
                        </div>
                        <h5 class="card-title mb-3"><a class="text-decoration-none text-dark stretched-link" href="#">Notifications</a></h5>
                        <p class="text-muted card-text text-sm">Choose notification preferences and how you want to be contacted</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

Views/User/Test.cshtml
<br />`<br /><br />
@{
    Layout = "_PagesLayout"; 

}


<form method="post" enctype="multipart/form-data">

    <input type="file" id="files"
           name="files" multiple />

    <input type="button"
           id="upload"
           value="Upload" />

</form>

@section Scripts{ 
    <script>
        $(document).ready(function () {

            $("#upload").click(function (evt) {

                var fileUpload = $("#files").get(0);

                var files = fileUpload.files;

                var data = new FormData();

                for (var i = 0; i < files.length; i++) {

                    data.append(files[i].name, files[i]);

                }

                $.ajax({

                    type: "post",

                    url: "/Notification/FileNotification",

                    contentType: false,

                    processData: false,

                    data: data,

                    success: function (message) {

                        alert(message);

                    },

                    error: function () {

                        alert("There was error uploading files!");

                    }

                });

            });

        });
    </script>
}